FROM ubuntu:18.04

MAINTAINER devplayg <devplayg@gmail.com>

RUN sed -i s#archive\.ubuntu\.com#mirror.kakao.com#g /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y vim net-tools inetutils-ping telnet curl git
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*